"""

  Filename: tool_MD5.py
  Created by: DuckyDuck1553 (11Apr15)

"""

import hashlib
import time
import os

FILE_LIST = [
    "coginvasion.bin",
    "coginvasion.exe",
    "icon.ico",
    "toonmono.cur",
    "phase_0.mf",
    "phase_3.mf",
    "phase_3.5.mf",
    "phase_4.mf",
    "phase_5.mf",
    "phase_5.5.mf",
    "phase_6.mf",
    "phase_7.mf",
    "phase_8.mf",
    "phase_9.mf",
    "phase_10.mf",
    "phase_11.mf",
    "phase_12.mf",
    "phase_13.mf",
    "phase_14.mf",
    "winter.mf"
]

monthNum2monthAbr = {
    '01': 'Jan',
    '02': 'Feb',
    '03': 'Mar',
    '04': 'Apr',
    '05': 'May',
    '06': 'Jun',
    '07': 'Jul',
    '08': 'Aug',
    '09': 'Sep',
    '10': 'Oct',
    '11': 'Nov',
    '12': 'Dec'
}

date = time.strftime("%d-%m-%Y")
day, monthNum, year = date.split('-')
month = monthNum2monthAbr[monthNum]
dateStr = "({0}{1}{2})".format(day, month, year[-2:])

print dateStr

HEADING = """// This file was automatically generated by tool_MD5.py
// Created on: {0}

""".format(dateStr)

info_file = open("file_info.txt", "w+")
info_file.write(HEADING)
info_file.flush()

for fileName in FILE_LIST:
    fileNameToWrite = str(fileName)
    if ".dll" in fileName or ".asi" in fileName:
        fileName = "../Panda3D-CI/bin/" + fileName
    elif "panda3d" in fileName:
        fileName = "../Panda3D-CI/" + fileName
    md5 = hashlib.sha1(open(fileName, 'rb').read()).hexdigest()
    size = os.path.getsize(fileName)
    what2PutInFile = fileNameToWrite + " " + str(md5)# + " " + str(size)
    print what2PutInFile
    info_file.write(what2PutInFile + "\n")
    info_file.flush()

info_file.close()
del info_file
